name: image_cache_plugin_example
description: Demonstrates the image_cache_plugin package.
publish_to: 'none'

environment:
  sdk: ^3.11.5

dependencies:
  equatable: 2.1.0
  fpdart: 1.2.0
  flutter:
    sdk: flutter
  get_it: 9.2.1
  image_cache_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: 1.0.5

flutter:
  uses-material-design: true
