include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    discarded_futures: true
    only_throw_errors: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unawaited_futures: true
